name: "D1 - Whole project: Destroy"
run-name: "D1 - Whole project: Destroy"

on: 
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

jobs:
  #################################
  ######## Destroy project ########
  #################################
  deploy_app:
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '8a'
      ACTION: 'd'
    secrets: inherit
    
  github_sync:
    needs: [
      deploy_app
    ]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '1a'
      ACTION: 'd'
    secrets: inherit