name: "D1 - Whole project: Destroy"
run-name: "D1 - Whole project: Destroy"

on: 
  workflow_dispatch:
    inputs:
      CONFIRMATION:
        required: true
        type: string
        description: "Vazio aborta. Qualquer valor confirma."

jobs:
  #################################
  ######## Destroy project ########
  #################################
  rds_mysql:
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3b'
      ACTION: 'd'
    secrets: inherit

  bastion:
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '3a'
      ACTION: 'd'
    secrets: inherit

  vpc_network:
    needs: [bastion, rds_mysql]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '2a'
      ACTION: 'd'
    secrets: inherit

  github_sync:
    needs: [vpc_network, bastion, rds_mysql]
    uses: ./.github/workflows/single-sub-project-run.yml
    with:
      RESOURCE: '1a'
      ACTION: 'd'
    secrets: inherit